import { Command } from "commander";
import * as path from "path";
import * as fs from "fs-extra";

export const testCommand = new Command("test")
  .description("Executes the automated smart contract test suite")
  .option(
    "--gas",
    "Enable gas profiler to report gas used by transactions during tests",
  )
  .action(async (options: { gas?: boolean }) => {
    try {
      console.log("Triggering automated contract compilation...");
      const { runCompile } = await import("./compile");
      await runCompile();

      const testDir = path.resolve(process.cwd(), "test");
      if (!(await fs.pathExists(testDir))) {
        console.error(`Error: 'test' directory not found at ${testDir}.`);
        process.exit(1);
      }

      const suppressWarning = (args: any[]) => {
        const msg = args.join(" ");
        return (
          msg.includes("uws_win32") ||
          msg.includes("Falling back to a NodeJS implementation") ||
          msg.includes("This version of \u00B5WS") ||
          msg.includes("This version of") ||
          msg.includes("uws-js-unofficial") ||
          msg.includes("Require stack:") ||
          msg.includes("Cannot find module")
        );
      };

      const originalConsoleError = console.error;
      console.error = (...args: any[]) => {
        if (suppressWarning(args)) return;
        originalConsoleError(...args);
      };

      const originalConsoleWarn = console.warn;
      console.warn = (...args: any[]) => {
        if (suppressWarning(args)) return;
        originalConsoleWarn(...args);
      };

      const originalConsoleLog = console.log;
      console.log = (...args: any[]) => {
        if (suppressWarning(args)) return;
        originalConsoleLog(...args);
      };

      console.log("Starting ephemeral CointMU DevNet for testing...");
      const ganache = require("ganache");
      const port = 8555;
      const serverOptions = {
        chain: { chainId: 1912 },
        server: { port },
        wallet: { totalAccounts: 10, defaultBalance: 100 },
        logging: { quiet: true },
        miner: { instamine: "strict" },
      };

      const server = ganache.server(serverOptions);

      await new Promise<void>((resolve, reject) => {
        server.listen(port, (err: Error | null) => {
          if (err) return reject(err);
          resolve();
        });
      });

      try {
        const provider = server.provider;
        const initialAccounts = provider.getInitialAccounts();
        const accountAddresses = Object.keys(initialAccounts);

        if (accountAddresses.length === 0) {
          throw new Error("No initial accounts generated by Ganache.");
        }

        const primaryAccount = initialAccounts[accountAddresses[0]];
        const privateKey = primaryAccount.secretKey;

        const injectedEnv = {
          ...process.env,
          CMU_RPC_URL: `http://127.0.0.1:${port}`,
          CMU_CHAIN_ID: "1912",
          PRIVATE_KEY: privateKey,
        };

        const { execFileSync } = require("child_process");
        const isWin = process.platform === "win32";

        // Check if there are JS or TS files in the test directory
        const hasTsFiles = fs
          .readdirSync(testDir)
          .some((f: string) => f.endsWith(".ts"));
        const runnerArgs = hasTsFiles
          ? ["mocha", "-r", "ts-node/register", "test/**/*.ts"]
          : ["mocha", "test/**/*.js"];

        console.log(`\n========================================`);
        console.log(`Running tests via Mocha`);
        console.log(`========================================\n`);

        execFileSync("npx", runnerArgs, {
          stdio: "inherit",
          env: injectedEnv,
          shell: isWin,
        });

        console.log("\nAll tests executed successfully.");
      } finally {
        if (options.gas) {
          try {
            console.log(
              "\n=========================================================================================",
            );
            console.log("Gas Profiler Report");
            console.log(
              "=========================================================================================",
            );
            console.log(
              "| Block | Transaction Hash                                                   | Gas Used |",
            );
            console.log(
              "-----------------------------------------------------------------------------------------",
            );

            const { ethers } = require("ethers");
            const rpcProvider = new ethers.JsonRpcProvider(
              `http://127.0.0.1:${port}`,
            );
            const latestBlock = await rpcProvider.getBlockNumber();
            let totalGas = 0n;

            for (let i = 1; i <= latestBlock; i++) {
              const block = await rpcProvider.getBlock(i);
              if (block && block.transactions) {
                for (const txHash of block.transactions) {
                  const receipt =
                    await rpcProvider.getTransactionReceipt(txHash);
                  if (receipt) {
                    const gasUsed = receipt.gasUsed;
                    totalGas += gasUsed;
                    console.log(
                      `| ${i.toString().padEnd(5)} | ${txHash} | ${gasUsed.toString().padEnd(8)} |`,
                    );
                  }
                }
              }
            }
            console.log(
              "-----------------------------------------------------------------------------------------",
            );
            console.log(`Total Gas Used: ${totalGas.toString()}\n`);
          } catch (e) {
            console.error("Failed to generate gas report", e);
          }
        }
        await server.close();
        console.log("Ephemeral test network successfully shut down.");
      }
    } catch (error) {
      console.error("\n[!] Test suite failed:");
      console.error(error instanceof Error ? error.message : String(error));
      process.exit(1);
    }
  });
